Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -58,9 +58,15 @@ jobs:
           echo "Run attempt: ${{ github.run_attempt }}"
           echo "Workflow: ${{ github.workflow }}"
           echo "Run number: ${{ github.run_number }}"
-          if [ "${{ needs.info.result }}" = "skipped" ]; then
-            echo "Running with is-rerun: $is_rerun_failed"
-          if
+          if [ "${{ needs.prepare.result }}" = "skipped" ]; then
+            echo "⚠️ prepare job was skipped, not executed."
+            exit 1
+          elif [ "${{ needs.prepare.result }}" = "success" ]; then
+            echo "✅ prepare job executed successfully."
+          else
+            echo "❌ prepare job failed."
+            exit 1
+          fi
 
       - name: Run a one-line script
         run: |
